[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "manage-profiles"
version = "0.0.1"
dependencies = [
    "boto3",
    "click",
    "tabulate",
]

[tool.setuptools.packages]
find = {}

[project.scripts]
aws-profile-manager = "src.cli:main"
